version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build # Ensure this matches your React app's output directory
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
